name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scan: ^1.4.3
  web3dart: ^2.3.0
  shared_preferences: ^2.0.7
  cupertino_icons: ^1.0.2
  eth_sig_util: ^0.0.3
  json_annotation: ^4.7.0
  wallet_connect_v2:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
