name: wallet_connect
description: Wallet Connect sdk for dart.
version: 2.0.0
homepage: https://github.com/Orange-Wallet/wallet-connect-dart

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  web_socket_channel: ^2.2.0
  logger: ^1.1.0
  convert: ^3.1.0
  cryptography: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bs58: ^1.0.2
  ed25519_edwards: ^0.3.1
  x25519: ^0.1.1
  pointycastle: ^3.6.2
  yx_tool: ^0.1.2

dev_dependencies:
  test:
  lints: ^2.0.0
  build_runner: ^2.0.0
  hive_generator:
  json_serializable: ^6.0.0
